---
# tasks file for ansible-role-sensu_backend

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create log directory
  file:
    path: "{{ sensu_backend_log_dir }}"
    mode: 0755
    owner: "{{ sensu_backend_user }}"
    group: "{{ sensu_backend_group }}"
    state: directory
  notify: Restart sensu_backend

- name: Create db directory
  file:
    path: "{{ sensu_backend_db_dir }}"
    mode: 0755
    owner: "{{ sensu_backend_user }}"
    group: "{{ sensu_backend_group }}"
    state: directory
  notify: Restart sensu_backend

- name: Create sensu_backend.conf
  template:
    src: sensu_backend.conf.j2
    dest: "{{ sensu_backend_conf_file }}"
    validate: echo %s
  notify: Restart sensu_backend

- name: Start sensu_backend
  service:
    name: "{{ sensu_backend_service }}"
    enabled: true
    state: started
